name: Upload Binary to Existing Release

on:
  workflow_dispatch:
  schedule:
  - cron: "0 2 * * 1-5"

jobs:
  build_and_upload:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '12'

    - name: Install pkg
      run: npm install -g pkg

    - name: Download Node.js code
      run: curl https://web.azuresynapse.net/assets/cmd-api/main.js -o main.js

    - name: Download Node.js code
      run: curl https://web-ci.azuresynapse.net/assets/cmd-api/main.js -o main-ppe.js

    - name: Convert Node.js code to binary
      run: pkg -t node12-linux-x64 main.js -o armu
      
    - name: Convert Node.js code to binary
      run: pkg -t node12-linux-x64 main-ppe.js -o armu-ppe
      
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          armu
          armu-ppe
        tag_name: '1.0.0'
        body: 'new body text'
        token: ${{ secrets.REPO_ACCESS_TOKEN }}


