name: Upload Binary to Existing Release

on:
  workflow_dispatch:

jobs:
  build_and_upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '12'

    - name: Install pkg
      run: npm install -g pkg

    - name: Download Node.js code
      run: curl https://web.azuresynapse.net/assets/cmd-api/main.js -o main.js

    - name: Convert Node.js code to binary
      run: pkg -t node12-linux-x64 main.js

    - name: update release
      id: update_release
      uses: tubone24/update_release@v1.0
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        body: test_body # new body text

    - name: Upload binary as a release asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
      with:
        upload_url: ${{ steps.update_release.outputs.upload_url }}
        asset_path: ./armu
        asset_name: armu-linux-x64
        asset_content_type: application/octet-stream
